services:
  - type: web
    name: node-express-render-api
    env: node
    buildCommand: "npm install"
    startCommand: "node index.js"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: mydb
          property: connectionString
